### ISSUE TITLE
How to remove registrations when app is reinstalled or device is wiped?

### ISSUE THREAD

**Issue by johnqh** [Azure/azure-notificationhubs#10]
Let's same I registered a device token with a tag (which is a user account email) when the user log in.

The user may remove the app. He may wipe the device when he upgrade to a new device.

Eventually, the tag (user account) will have multiple devices registered for it.

How do we clean up those unused device tokens?

This is relevant to the pricing model. The Basic tier has 3K tag limit but tags with five or fewer devices do not accrue to the tag limit.

Also, I think eventually it will become a performance issue.

**Comment by adityat90** [comment]
I've been facing this same issue with azure.
@johnqh Have you made any progress in this regard?

**Comment by brannon** [comment]
You can specify an expiration for each registration. On app start you can refresh the registration. Then if the device isn't seen for a while, the registration will be removed automatically.

The underlying platform (APNS, FCM) will also invalidate device tokens. If a notification targets an expired / invalid device token, then Notification Hubs will: a. return the expired / invalid device token status to the caller (for Standard tier namespaces), and b. mark the device token as expired.

Once the device token is marked as expired, Notification Hubs will no longer attempt to send notifications to that device token.

I realize this question is super old, but I'm going through and trying to close out old issues and I hope this information helps!
