### ISSUE TITLE
Abandonware

### ISSUE THREAD

**Issue by mandrachek** [Azure/azure-notificationhubs#12]
Is this abandoned? The azure mobile services sdk 2, at least for android, integrates the functionality for registering, and no longer relies on this library.

**Comment by ysxu** [comment]
Not at all! We used to ship Notification Hubs SDK with the Mobile Services SDK, though the latter never took a dependency on the former. The registration functionality in Mobile Services SDK you see is for Mobile Services push, while Notification Hubs SDK provides convenience to users who are working with NH directly.

**Comment by mandrachek** [comment]
@ysxu great, thanks.
