### ISSUE TITLE
Azure Notification Hub MSDN Documentation Bug

### ISSUE THREAD

**Issue by mcm-ham** [Azure/azure-notificationhubs#20]
I'm not sure where to file this bug, but on this page:
https://msdn.microsoft.com/en-us/library/azure/dn223265.aspx

The template registration example contains:
```xml
<WnsHeaders>
  <WNSHeader>
    <Header>X-WNS-Type</Header>
    <Value>wns/tile</Value>
  </WNSHeader>
<WnsHeaders>
```

And this fails for me with an error about missing X-WNS-Type. If I change `WNSHeader` to `WnsHeader` then it works fine.

**Comment by wesmc7777** [comment]
Thank you for reporting it.  I've updated that documentation to resolve it.
