### ISSUE TITLE
ios9 support

### ISSUE THREAD

**Issue by robertocan** [Azure/azure-notificationhubs#21]
Hello!

Could someone help me building iOS/bin/WindowsAzureMessaging.framework.zip with io9 support?
Sorry, but I use cordova and I don't know very much about xcode deploy and I am having some trouble with the new xcode.

Tks

**Comment by Pajk** [comment]
Hi @robertocan, just download the code from this repo and compile by running `buildAndRunCIT.command` in the terminal. Then copy the framework from `WindowsAzureMessaging/build/Release-iphoneos/WindowsAzureMessaging.framework` to your project.  Worked for me on iOS 9.1.

**Comment by robertocan** [comment]
Thank you @Pajk, I did it last week and it worked.
I also had to modify the project by adding the platforms arm7s, arm64 and the option ENABLE_BITCODE=YES to compile and use this library on iOS9.1.
