### ISSUE TITLE
Visual Studio error

### ISSUE THREAD

**Issue by satishknl** [Azure/azure-notificationhubs#35]
Hi,
Developer team is facing issue when they connect notification hub to Visual studio. The azure user account which added in visual studio has owner privileges. 
Need your help.
Attached the screenshot
Thanks
![errorvisualstudio](https://user-images.githubusercontent.com/26115330/28121917-428d394e-673a-11e7-89f2-ec6cee88348a.png)

**Comment by Alessar** [comment]
Hi @satishknl . Could You please notify if issue still exists or not?

**Comment by Alessar** [comment]
Issue was closed after a lot of time. Maybe it have been already resolved.
Otherwise please reopen issue and add more additional information.
