### ISSUE TITLE
[iOS] leakage of confidential information 

### ISSUE THREAD

**Issue by vikram-ma** [Azure/azure-notificationhubs#38]
There is a security vulnerability where device tokens can be read from iOS device since it is stored in NSUserDefaults, particularly below file,
iOS/WindowsAzureMessaging/WindowsAzureMessaging/Helpers/SBLocalStorage.m

Any plan to fix this?

**Comment by brannon** [comment]
Push tokens are not considered sensitive. There are no plans to change the storage implementation at this time.
