### ISSUE TITLE
Bitcode is not full enabled

### ISSUE THREAD

**Issue by VicZhang1** [Azure/azure-notificationhubs#40]
Hi,

I get an error as below:

> ld: bitcode bundle could not be generated because '/Users/Vic/projects/projecta/WindowsAzureMessaging.framework/WindowsAzureMessaging(SBNotificationHub.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/Vic/projects/projecta/WindowsAzureMessaging.framework/WindowsAzureMessaging' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

But otool shows it contains bitcode:

> Vic:projecta Vic$ (otool -arch arm64 -l WindowsAzureMessaging.framework/WindowsAzureMessaging | grep LLVM) || echo "no bitcode"
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM
>    segname __LLVM

Any ideas?

Thanks,
-
Vic

**Comment by VicZhang1** [comment]
I download the WindowsAzureMessaging.framework from https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-ios-apple-push-notification-apns-get-started#prerequisites, the real download link is http://go.microsoft.com/fwlink/?LinkID=799698&clcid=0x409.

**Comment by qliu95114** [comment]
Hi Vic, can you share more context or solution details, one of my friend use sample 
https://github.com/Azure/azure-notificationhubs-samples/tree/master/iOS/GetStartedNH/GetStarted
there is no problem to compile and build

**Comment by mszaczhang** [comment]
The new version (2017/11/28) package is a little smaller than old (2016/06/30) one.  
We can also see slight different in SBNotificationHub.h.  Old version have two more lines.

**Comment by VicZhang1** [comment]
Hi @mszaczhang & @qliu95114 , thanks for your reply, my setting is 
![image](https://user-images.githubusercontent.com/2956318/40285487-2f381306-5ccf-11e8-965e-d9c507c8555d.png)

And, as I said above, the framework I am using is http://go.microsoft.com/fwlink/?LinkID=799698&clcid=0x409. After uncompressed, the size of framework is about 4.2 MB.

**Comment by mszaczhang** [comment]
What's your Xcode version?

**Comment by VicZhang1** [comment]
Thanks @mszaczhang , I am using Xcode 9, now I upgraded it to Xcode 9.1 last Friday.

**Comment by VicZhang1** [comment]
@mszaczhang @qliu95114 , I created an empty project which reference the same WindowsAzureMessaging.framework, it can archive(and build) successfully,  I compared this test project settings with mine, finally, I find if I turn “Write Link Map File” (`LD_GENERATE_MAP_FILE`) off, our project can archive successfully, though I don't understand what this option mean.

However, thanks for your help.

**Comment by AdaptiveTechnologies** [comment]
I'm having the same issue... I can build, but I can't archive without this error: bitcode bundle could not be generated because '/Users/_______/Journey/Journey/Libraries/WindowsAzureMessaging.framework/WindowsAzureMessaging(SBNotificationHub.o)' was built without full bitcode.

**Comment by VicZhang1** [comment]
@mszaczhang  @qliu95114 , If I remove WindowsAzureMessaging.framework and related code, then I can archive successfully. So I believe there is something in WindowsAzureMessaging.framework.

**Comment by VicZhang1** [comment]
I own another framework, when I tried to enable bitcode, I also got the same error with the one that currently I am getting from WindowsAzureMessaging. Finally I compiler myself framework like:

> xcodebuild -project ${PROJECT_NAME}.xcodeproj -target ${PROJECT_NAME} -sdk iphoneos -configuration ${CONFIGURATION} OTHER_CFLAGS="-fembed-bitcode" BITCODE_GENERATION_MODE=bitcode build 2>&1

After I added **OTHER_CFLAGS="-fembed-bitcode" BITCODE_GENERATION_MODE=bitcode** to build my framework, the error went away.

@qliu95114 , I know your developers are all expert, but do you mind to check with them if this works?

By the way, "Archive" is:
1. Select the target that you want to build
2. Select "Generic iOS devices"
3. Select "Product" -> "Archive"

like: 
![image](https://user-images.githubusercontent.com/2956318/40467993-874a3858-5f5e-11e8-9c08-c1546bf8468e.png)

**Comment by BillCarlson** [comment]
I wanted to leave a comment here that I was getting a similar issue regarding not being able to link with arm64, and it took quite a lot of effort to narrow down, but the solution was very simple.

The root cause was that I was building the WindowsAzureMessaging.framework file/directory and adding it to git.  This directory contains a "WindowsAzureMessaging" file, which is the library itself, and git was not recognizing it as a binary file.  It was being treated as a text file, and this pretty much just messed everything up.  I could still run the 'lipo' command and 'otool' command and usually get valid data out of them.  Sometimes I would get an error about reaching the end of the file and it being corrupt, but only after fully resyncing from git.

The solution is very simple - I created a .gitattributes file within the WindowsAzureMessaging.framework folder, and its contents are "WindowsAzureMessaging binary".  Then I re-copied over a new version of the binary into git, and everything started building fully.

**Comment by stankovski** [comment]
We have fixed the build settings and re-published the SDK at http://aka.ms/aznh-ios-sdk.
