### ISSUE TITLE
Android Pie migration

### ISSUE THREAD

**Issue by V1rus999** [Azure/azure-notificationhubs#45]
From the android developers website: "With Android 6.0, we removed support for the Apache HTTP client. Beginning with Android 9, that library is removed from the bootclasspath and is not available to apps by default."

There is a workaround where you have to add: <uses-library android:name="org.apache.http.legacy" android:required="false"/> to the manifest.

Are there any plans to remove apache and use something else?

**Comment by Prashanthlkv** [comment]
**There is a workaround where you have to add: to the manifest?**
Could you please let me know what is the workaround to resolve this issue?
I tried with OS Android 9, it's not working.

**Comment by V1rus999** [comment]
@Prashanthlkv 

Apologies I thought I added it to the OP. 

`<uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />`

Needs to be added to your manifest file under the application tag.

**Comment by Prashanthlkv** [comment]
@V1rus999 
Thanks for the quick response . It's working fine now. Still I feel this should be handled at SDK end. What is you thoughts on this?

**Comment by V1rus999** [comment]
@Prashanthlkv I haven't looked at why Notification Hubs uses the apache http library, but my thought is they can replace it with something else.

**Comment by acastr7** [comment]
Getting this error too, my error logs show "Didn't find class "org.apache.http.Header" on path: DexPathList[[zip file ...."

The work around stated above worked. You can find the Android documentation about this issue here https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p

**Comment by stankovski** [comment]
Duplicate issue #46
We have fixed the SDK and upload an update to bintray
