### ISSUE TITLE
Android Azure notification hub SDK is not working in Android Pie

### ISSUE THREAD

**Issue by Prashanthlkv** [Azure/azure-notificationhubs#46]
Below are the SDK details: 
**Mavel url:** 
"http://dl.bintray.com/microsoftazuremobile/SDK" 
**Dependencies:** 
compile 'com.microsoft.azure:notification-hubs-android-sdk:0.4@aar' 
compile 'com.microsoft.azure:azure-notifications-handler:1.0.1@aar'

**Steps to reproduce:** 
1. Get GCM/FCM token 
2. Create instance of NotificationHub 
3. Call method "registerTemplate" using the instance of NotificationHub along with the required parameters.

**Error:**

**Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/net/http/AndroidHttpClient**; at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:217) at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:178) at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:134) at com.microsoft.windowsazure.messaging.NotificationHub.refreshRegistrationInformation(NotificationHub.java:296) at com.microsoft.windowsazure.messaging.NotificationHub.registerInternal(NotificationHub.java:390) at com.microsoft.windowsazure.messaging.NotificationHub.registerTemplate(NotificationHub.java:196)

**Comment by stankovski** [comment]
We have fixed the issue and published an updated SDK on bintray.

**Comment by acastr7** [comment]
Will there be an update to https://www.nuget.org/packages/Xamarin.Azure.NotificationHubs.Android to support this fix?

**Comment by brannon** [comment]
@acastr7 we have contacted the team that owns the Xamarin package and let them know we released an updated SDK version for Android P.

They have created a bug to track this: https://github.com/xamarin/XamarinComponents/issues/480
