### ISSUE TITLE
Failure while sending direct FcmNotification to multiple Android devices

### ISSUE THREAD

**Issue by skolesni** [Azure/azure-notificationhubs#72]
This relates to `Microsoft.Azure.NotificationHubs` nuget v 3.0.1

I can successfully send notifications to single device using method `SendDirectNotificationAsync` of the `Microsoft.Azure.NotificationHubs.NotificationHubClient` class

The `SendDirectNotificationAsync` has the following 2 overloads:

1. `public Task<NotificationOutcome> SendDirectNotificationAsync(Notification notification, string deviceHandle)`
2. `public async Task<NotificationOutcome> SendDirectNotificationAsync(Notification notification, IList<string> deviceHandles)`

Both work great for Apple, however for Android the first one works, but the second fails

As we only support iOS and Android we create notification using either:

`var notification = new AppleNotification(jsonPayload);`
or 
`var notification = new FcmNotification(jsonPayload);`

and then for single device perform:
`var result = await this.notificationHubClient.SendDirectNotificationAsync(notification, deviceToken);`

As stated above it works great for both iOS and Android, however the following works for iOS but not for Android:

`var result = await this.notificationHubClient.SendDirectNotificationAsync(notification, new List<string> { deviceToken });`

The `System.ArgumentException` states:

`"The HTTP header 'ServiceBusNotification-Format' has an invalid value: 'fcm'. Allowed values are 'windows', 'apple', 'gcm', 'template', or 'windowsphone'.TrackingId:8b7be203-4619-4247-994a-496c766ca2b5_G0,TimeStamp:2/21/2019 10:58:05 AM"`

Unfortunately, the GCM gateway listed in the allowed values is deprecated and will be shut down on 11/04/2019. The Azure Hub has full support for the FCM technology which replaces GCM. I have used other scenarios with FCM, such as with direct registrations and it works great. However this issue is stopping us sending notifications to multiple devices (let say a batch of 500).

Could you please assist with this problem, as this is an URGENT matter due to expiring GCM?
Thank you.

**Comment by jwargo** [comment]
@skolesni we're aware of the pending shutdown of GCM and plan to refresh the SDKs before the service shuts down.  We're going to split the SDKs into separate platforms, so expect to see a new Android repository in the near future.

**Comment by skolesni** [comment]
@jwargo thank you for responding quickly. It is good to know that a new update is coming. Could you please confirm whether the issue I am reffering to is being addressed? Is it a known bug? We are integrating Notification Hub in order to improve performance while sending direct notifications only, and if this feature is not available by the end of March, we are simply not migrating to Azure Hubs. Thank you.

**Comment by jwargo** [comment]
@skolesni I can't, not technical enough (I'm a JavaScript and JavaScript-driven Native developer). But I'll ask the team to take a look.

**Comment by jwargo** [comment]
@skolesni we think it's a bug, we'll triage it as part of our refresh. Stay tuned.

**Comment by skolesni** [comment]
Great @jwargo thank you for looking into this and reassuring. Have a good day.
