### ISSUE TITLE
Publish in Maven Repository?

### ISSUE THREAD

**Issue by xdansmith** [Azure/azure-notificationhubs#9]
Are there any plans to publish this in the Maven repository to make it easier for developers that use Maven for their builds to reference Notification Hubs?

Thanks!

Dan

**Comment by mandrachek** [comment]
bump

**Comment by mandrachek** [comment]
It appears there is a pull request for converting the project to gradle and AndroidStudio, which is a good first step towards this @ https://github.com/Azure/azure-notificationhubs/pull/11 -- However the pull request seems to be missing the bits, at least judgjing by what's being done with the mobile services sdk, to enable publishing binary artifacts to jcenter (but perhaps this project is just being setup differently?)

**Comment by ysxu** [comment]
@mandrachek We are still in the process of updating the SDK, but yes, like the Mobile Services Android SDK, we want to get Notification Hubs SDK up at jCenter as well. Maven would be the next step.
